name: workproject
description: "Development of Application for Identity and Location Authentication."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'



# ------------------- PACKAGE DEPENDENCIES ------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utilitiy Packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  lottie: ^2.7.0


# ------------------- DEV DEPENDENCIES ------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1



# ------------------- FLUTTER CONFIG ------------------- #
flutter:

  uses-material-design: true

  # ------------------- LOCAL ASSETS ------------------- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/navigation_menu/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/signup_images/
    


  # ------------------- LOCAL FONTS ------------------- #
#fonts:
  #- family:
    #fonts:
      #-assets: fonts/___.ttf
      #style: italic
      #weight:
      #สร้างfolder fonts ใน assets แล้วใส่.ttfลงไป