name: workproject
description: "Development of Application for Identity and Location Authentication."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'



# ------------------- PACKAGE DEPENDENCIES ------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utilitiy Packages
  http: ^1.2.0
  intl: ^0.18.0
  logger: ^2.0.2
  lottie: ^2.4.0
  shimmer: ^3.0.0
  rive: ^0.11.3
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.8
  smooth_page_indicator: ^1.1.0
  calendar_timeline_sbk: ^1.1.7
  giffy_dialog: ^2.0.0+2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.0
  
  
  cached_network_image: ^3.3.1
  permission_handler: ^11.2.0
  network_info_plus: ^4.1.0+1
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  


# ------------------- DEV DEPENDENCIES ------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


# ------------------- FLUTTER CONFIG ------------------- #
flutter:

  uses-material-design: true

  # ------------------- LOCAL ASSETS ------------------- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/RiveAssets/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/signup_images/
    - assets/images/home_images/
    - assets/images/animations/
    


  # ------------------- LOCAL FONTS ------------------- #
#fonts:
  #- family:
    #fonts:
      #-assets: fonts/___.ttf
      #style: italic
      #weight:
      #สร้างfolder fonts ใน assets แล้วใส่.ttfลงไป