// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPebX3WxaArYwFRQvBZkrsV4CSRt-FxXo',
    appId: '1:151641264000:web:4b409e9c89a18cc2637b65',
    messagingSenderId: '151641264000',
    projectId: 'p4projectapp',
    authDomain: 'p4projectapp.firebaseapp.com',
    storageBucket: 'p4projectapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwPwotHqbiDNd4LnGszHNovnA88tFg2fg',
    appId: '1:151641264000:android:81cd6109b8aecc17637b65',
    messagingSenderId: '151641264000',
    projectId: 'p4projectapp',
    storageBucket: 'p4projectapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wxIYfpsC7Tkw5cSrHR5UT5wzSlFryjo',
    appId: '1:151641264000:ios:054ad8a25395aa45637b65',
    messagingSenderId: '151641264000',
    projectId: 'p4projectapp',
    storageBucket: 'p4projectapp.appspot.com',
    androidClientId: '151641264000-4prolrqr6vfj1p8ojnenjokonam4nqot.apps.googleusercontent.com',
    iosClientId: '151641264000-fp4ulruuf756d69dc675tk2s5bugmoqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.workproject',
  );
}
